/**
 * EMAIL CENTER - Shared Styles
 * Dark theme (#09090b), inline styles only
 */

export const s = {
  // Layout
  container: {
    padding: "24px",
    maxWidth: "1800px",
    margin: "0 auto",
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: "16px",
    height: "100%",
  },
  header: {
    display: "flex" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
  },
  title: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "12px",
    color: "#e2e8f0",
  },
  h2: { margin: 0, fontSize: "1.5rem", fontWeight: 600 },
  subtitle: { margin: 0, fontSize: "0.875rem", color: "#71717a" },
  headerActions: {
    display: "flex" as const,
    gap: "8px",
    alignItems: "center" as const,
  },
  headerChips: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    flexWrap: "wrap" as const,
  },
  headerChip: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "5px",
    padding: "4px 10px",
    borderRadius: "6px",
    fontSize: "0.72rem",
    fontWeight: 500,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "#94a3b8",
    cursor: "pointer" as const,
    whiteSpace: "nowrap" as const,
  },
  headerChipValue: {
    fontWeight: 700,
    fontSize: "0.8rem",
  },
  headerChipOverdue: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "5px",
    padding: "4px 10px",
    borderRadius: "6px",
    fontSize: "0.72rem",
    fontWeight: 600,
    background: "#450a0a",
    border: "1px solid #991b1b",
    color: "#fca5a5",
    cursor: "pointer" as const,
    whiteSpace: "nowrap" as const,
  },
  btnIcon: {
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#a1a1aa",
    padding: "10px",
    borderRadius: "8px",
    cursor: "pointer" as const,
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  btnPrimary: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "6px",
    background: "rgba(212, 168, 67, 0.2)",
    border: "1px solid rgba(212, 168, 67, 0.4)",
    color: "#a5b4fc",
    padding: "8px 16px",
    borderRadius: "8px",
    fontSize: "0.85rem",
    fontWeight: 500,
    cursor: "pointer" as const,
  },

  // Tabs
  tabs: {
    display: "flex" as const,
    gap: "8px",
    background: "rgba(255, 255, 255, 0.02)",
    padding: "6px",
    borderRadius: "12px",
    width: "fit-content" as const,
  },
  tab: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "10px 20px",
    background: "transparent",
    border: "none" as const,
    color: "#71717a",
    fontSize: "0.875rem",
    borderRadius: "8px",
    cursor: "pointer" as const,
  },
  tabActive: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "10px 20px",
    background: "rgba(212, 168, 67, 0.15)",
    border: "none" as const,
    color: "#a5b4fc",
    fontSize: "0.875rem",
    borderRadius: "8px",
    cursor: "pointer" as const,
  },
  badge: {
    background: "rgba(239, 68, 68, 0.2)",
    color: "#fca5a5",
    padding: "2px 8px",
    borderRadius: "10px",
    fontSize: "0.75rem",
    fontWeight: 600,
  },

  // Stats
  statsRow: {
    display: "flex" as const,
    gap: "10px",
    flexWrap: "wrap" as const,
  },
  statCard: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "10px",
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "10px",
    padding: "10px 14px",
    cursor: "pointer" as const,
  },
  statCardActive: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "10px",
    background: "rgba(212, 168, 67, 0.1)",
    border: "1px solid rgba(212, 168, 67, 0.4)",
    borderRadius: "10px",
    padding: "10px 14px",
    cursor: "pointer" as const,
  },
  statValue: { fontSize: "1.1rem", fontWeight: 700, color: "#e2e8f0" },
  statLabel: { fontSize: "0.7rem", color: "#71717a" },

  // Filter / Search
  filterRow: {
    display: "flex" as const,
    gap: "12px",
    alignItems: "center" as const,
    flexWrap: "wrap" as const,
  },
  searchBox: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "8px",
    padding: "8px 12px",
    flex: 1,
    maxWidth: "300px",
  },
  searchInput: {
    background: "transparent",
    border: "none" as const,
    color: "#e2e8f0",
    fontSize: "0.875rem",
    outline: "none" as const,
    width: "100%",
  },

  // Master-Detail Split
  splitContainer: {
    display: "flex" as const,
    flex: 1,
    minHeight: 0,
    overflow: "hidden" as const,
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "16px",
    background: "rgba(255, 255, 255, 0.02)",
  },
  listPane: {
    width: "40%",
    minWidth: "360px",
    overflow: "auto" as const,
    borderRight: "1px solid rgba(255, 255, 255, 0.08)",
  },
  detailPane: {
    flex: 1,
    overflow: "auto" as const,
    display: "flex" as const,
    flexDirection: "column" as const,
  },
  detailPlaceholder: {
    flex: 1,
    display: "flex" as const,
    flexDirection: "column" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: "12px",
    color: "#52525b",
    padding: "48px",
  },

  // Table
  tableCard: {
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "16px",
    overflow: "hidden" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  tableInline: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  th: {
    padding: "10px 12px",
    textAlign: "left" as const,
    fontSize: "0.65rem",
    fontWeight: 600,
    color: "#71717a",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
    background: "rgba(0, 0, 0, 0.2)",
  },
  td: {
    padding: "10px 12px",
    fontSize: "0.8rem",
    color: "#e2e8f0",
    borderBottom: "1px solid rgba(255, 255, 255, 0.04)",
  },
  row: { cursor: "pointer" as const, transition: "background 0.15s" },
  rowHover: { background: "rgba(255, 255, 255, 0.03)" },
  rowUnread: { background: "rgba(212, 168, 67, 0.05)" },
  rowSelected: { background: "rgba(212, 168, 67, 0.12)" },
  loading: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    gap: "12px",
    padding: "48px",
    color: "#71717a",
  },
  empty: {
    display: "flex" as const,
    flexDirection: "column" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "48px",
    color: "#71717a",
  },
  loadMore: {
    display: "flex" as const,
    justifyContent: "center" as const,
    padding: "16px",
    borderTop: "1px solid rgba(255, 255, 255, 0.04)",
  },
  loadMoreBtn: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#a1a1aa",
    padding: "10px 20px",
    borderRadius: "8px",
    fontSize: "0.85rem",
    cursor: "pointer" as const,
  },

  // Cell styles
  typeBadge: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "4px",
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "0.65rem",
    fontWeight: 600,
  },
  fromCell: {
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: "1px",
  },
  fromName: { fontWeight: 500, fontSize: "0.8rem" },
  fromAddress: { fontSize: "0.7rem", color: "#71717a" },
  subjectCell: {
    maxWidth: "300px",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  installationLink: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "4px",
    color: "#a5b4fc",
    fontFamily: "monospace",
    fontSize: "0.75rem",
  },
  dateCell: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "4px",
    fontSize: "0.75rem",
    color: "#71717a",
  },
  mailboxBadge: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    padding: "2px 6px",
    borderRadius: "4px",
    fontSize: "0.65rem",
    fontWeight: 500,
  },
  mailboxInbox: {
    background: "rgba(59, 130, 246, 0.15)",
    color: "#93c5fd",
  },
  mailboxInstallation: {
    background: "rgba(16, 185, 129, 0.15)",
    color: "#6ee7b7",
  },
  mailboxOther: {
    background: "rgba(113, 113, 122, 0.15)",
    color: "#a1a1aa",
  },

  // Buttons
  assignBtn: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "4px",
    background: "rgba(212, 168, 67, 0.15)",
    border: "1px solid rgba(212, 168, 67, 0.3)",
    color: "#a5b4fc",
    padding: "4px 8px",
    borderRadius: "6px",
    fontSize: "0.7rem",
    cursor: "pointer" as const,
  },
  actionBtns: {
    display: "flex" as const,
    gap: "4px",
  },
  actionBtn: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    color: "#71717a",
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    cursor: "pointer" as const,
  },
  actionBtnDanger: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    background: "rgba(239, 68, 68, 0.1)",
    border: "1px solid rgba(239, 68, 68, 0.2)",
    color: "#f87171",
    width: "28px",
    height: "28px",
    borderRadius: "6px",
    cursor: "pointer" as const,
  },

  // Detail Panel
  detailHeader: {
    display: "flex" as const,
    justifyContent: "space-between" as const,
    alignItems: "flex-start" as const,
    padding: "20px 24px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
    background: "rgba(0, 0, 0, 0.2)",
  },
  detailHeaderInfo: {
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: "8px",
    flex: 1,
    minWidth: 0,
  },
  detailSubject: {
    fontSize: "1.1rem",
    fontWeight: 600,
    color: "#e2e8f0",
    margin: 0,
  },
  detailMeta: {
    display: "flex" as const,
    gap: "16px",
    flexWrap: "wrap" as const,
  },
  detailMetaItem: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "6px",
    fontSize: "0.8rem",
    color: "#a1a1aa",
  },
  detailMetaLabel: {
    fontSize: "0.7rem",
    color: "#71717a",
    minWidth: "24px",
  },
  detailActions: {
    display: "flex" as const,
    gap: "8px",
    alignItems: "center" as const,
    flexShrink: 0,
  },
  detailBody: {
    flex: 1,
    overflow: "auto" as const,
    padding: "24px",
  },
  detailBodyContent: {
    fontSize: "0.9rem",
    lineHeight: 1.6,
    color: "#e2e8f0",
    whiteSpace: "pre-wrap" as const,
    fontFamily: "inherit",
  },
  detailAiCard: {
    background: "rgba(212, 168, 67, 0.1)",
    border: "1px solid rgba(212, 168, 67, 0.2)",
    borderRadius: "10px",
    padding: "16px",
    marginBottom: "20px",
  },
  detailAiHeader: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    marginBottom: "8px",
  },
  detailAiTitle: {
    fontSize: "0.8rem",
    fontWeight: 600,
    color: "#a5b4fc",
  },
  detailAiSummary: {
    fontSize: "0.85rem",
    color: "#e2e8f0",
    lineHeight: 1.5,
  },
  iframeContainer: {
    background: "#ffffff",
    borderRadius: "8px",
    overflow: "hidden" as const,
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  iframe: {
    width: "100%",
    border: "none" as const,
    minHeight: "200px",
    background: "#ffffff",
  },

  // Attachments
  attachmentsSection: {
    marginTop: "20px",
    padding: "16px",
    background: "rgba(255, 255, 255, 0.03)",
    borderRadius: "10px",
    border: "1px solid rgba(255, 255, 255, 0.08)",
  },
  attachmentsList: {
    display: "flex" as const,
    gap: "8px",
    flexWrap: "wrap" as const,
    marginTop: "8px",
  },
  attachmentItem: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "6px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "8px",
    padding: "8px 12px",
    fontSize: "0.8rem",
    color: "#e2e8f0",
    cursor: "pointer" as const,
    textDecoration: "none" as const,
  },

  // Modal (shared)
  modalOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(0, 0, 0, 0.7)",
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    zIndex: 1000,
  },
  modal: {
    background: "#1a1a2e",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "16px",
    padding: "24px",
    width: "500px",
    maxWidth: "90vw",
    maxHeight: "80vh",
    overflow: "auto" as const,
  },
  modalHeader: {
    display: "flex" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    marginBottom: "20px",
  },
  modalTitle: {
    fontSize: "1.1rem",
    fontWeight: 600,
    color: "#e2e8f0",
  },
  modalClose: {
    background: "transparent",
    border: "none" as const,
    color: "#71717a",
    cursor: "pointer" as const,
    padding: "4px",
  },
  modalSearch: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "8px",
    padding: "10px 12px",
    marginBottom: "16px",
  },
  modalSearchInput: {
    background: "transparent",
    border: "none" as const,
    color: "#e2e8f0",
    fontSize: "0.9rem",
    outline: "none" as const,
    width: "100%",
  },

  // Installation list (assignment)
  installationList: {
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: "8px",
    maxHeight: "300px",
    overflow: "auto" as const,
  },
  installationItem: {
    display: "flex" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "8px",
    padding: "12px",
    cursor: "pointer" as const,
  },
  installationInfo: {
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: "2px",
  },
  installationId: {
    fontFamily: "monospace",
    color: "#a5b4fc",
    fontSize: "0.85rem",
    fontWeight: 600,
  },
  installationCustomer: {
    fontSize: "0.8rem",
    color: "#e2e8f0",
  },
  installationAddress: {
    fontSize: "0.75rem",
    color: "#71717a",
  },

  // Compose Modal
  composeModal: {
    background: "#1a1a2e",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "16px",
    width: "700px",
    maxWidth: "95vw",
    maxHeight: "90vh",
    overflow: "hidden" as const,
    display: "flex" as const,
    flexDirection: "column" as const,
  },
  composeHeader: {
    display: "flex" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    padding: "16px 24px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.08)",
    background: "rgba(0, 0, 0, 0.2)",
  },
  composeBody: {
    flex: 1,
    overflow: "auto" as const,
    padding: "20px 24px",
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: "12px",
  },
  composeField: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
  },
  composeLabel: {
    fontSize: "0.8rem",
    color: "#71717a",
    minWidth: "60px",
    flexShrink: 0,
  },
  composeInput: {
    flex: 1,
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "6px",
    padding: "8px 12px",
    color: "#e2e8f0",
    fontSize: "0.85rem",
    outline: "none" as const,
  },
  composeInputReadonly: {
    flex: 1,
    background: "rgba(255, 255, 255, 0.02)",
    border: "1px solid rgba(255, 255, 255, 0.06)",
    borderRadius: "6px",
    padding: "8px 12px",
    color: "#71717a",
    fontSize: "0.85rem",
  },
  composeTextarea: {
    width: "100%",
    minHeight: "200px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "8px",
    padding: "12px",
    color: "#e2e8f0",
    fontSize: "0.85rem",
    lineHeight: 1.6,
    resize: "vertical" as const,
    fontFamily: "inherit",
    outline: "none" as const,
  },
  composeFooter: {
    display: "flex" as const,
    justifyContent: "flex-end" as const,
    gap: "8px",
    padding: "16px 24px",
    borderTop: "1px solid rgba(255, 255, 255, 0.08)",
  },
  btnCancel: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "6px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#a1a1aa",
    padding: "8px 16px",
    borderRadius: "8px",
    fontSize: "0.85rem",
    cursor: "pointer" as const,
  },
  btnSend: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "6px",
    background: "rgba(212, 168, 67, 0.3)",
    border: "1px solid rgba(212, 168, 67, 0.5)",
    color: "#c7d2fe",
    padding: "8px 20px",
    borderRadius: "8px",
    fontSize: "0.85rem",
    fontWeight: 500,
    cursor: "pointer" as const,
  },
  btnSendDisabled: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "6px",
    background: "rgba(212, 168, 67, 0.1)",
    border: "1px solid rgba(212, 168, 67, 0.2)",
    color: "#D4A843",
    padding: "8px 20px",
    borderRadius: "8px",
    fontSize: "0.85rem",
    fontWeight: 500,
    cursor: "not-allowed" as const,
    opacity: 0.6,
  },

  // Template selector
  templateSelect: {
    width: "100%",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "6px",
    padding: "8px 12px",
    color: "#e2e8f0",
    fontSize: "0.85rem",
    outline: "none" as const,
    cursor: "pointer" as const,
  },

  // Detail modal (mobile fallback)
  detailModal: {
    background: "#1a1a2e",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    borderRadius: "16px",
    padding: "0",
    width: "800px",
    maxWidth: "95vw",
    maxHeight: "90vh",
    overflow: "hidden" as const,
    display: "flex" as const,
    flexDirection: "column" as const,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // 3-COLUMN LAYOUT
  // ═══════════════════════════════════════════════════════════════════════════════

  threeCol: {
    display: "flex" as const,
    flex: 1,
    minHeight: 0,
    overflow: "hidden" as const,
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "16px",
    background: "rgba(255, 255, 255, 0.02)",
  },
  colSidebar: {
    width: "230px",
    minWidth: "230px",
    overflow: "auto" as const,
    borderRight: "1px solid rgba(255, 255, 255, 0.08)",
    background: "rgba(0, 0, 0, 0.15)",
    display: "flex" as const,
    flexDirection: "column" as const,
  },
  colList: {
    width: "380px",
    minWidth: "320px",
    overflow: "auto" as const,
    borderRight: "1px solid rgba(255, 255, 255, 0.08)",
    display: "flex" as const,
    flexDirection: "column" as const,
  },
  colDetail: {
    flex: 1,
    minWidth: "300px",
    overflow: "auto" as const,
    display: "flex" as const,
    flexDirection: "column" as const,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // SIDEBAR
  // ═══════════════════════════════════════════════════════════════════════════════

  sbSection: {
    padding: "12px 14px 4px",
    fontSize: "9px",
    fontWeight: 700,
    color: "#475569",
    textTransform: "uppercase" as const,
    letterSpacing: "0.08em",
  },
  sbItem: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "6px 14px",
    cursor: "pointer" as const,
    fontSize: "0.78rem",
    color: "#a1a1aa",
    borderLeft: "2px solid transparent",
  },
  sbItemActive: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "6px 14px",
    cursor: "pointer" as const,
    fontSize: "0.78rem",
    color: "#e2e8f0",
    background: "#1e293b",
    borderLeft: "2px solid #EAD068",
  },
  sbLabel: {
    flex: 1,
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  sbSub: {
    fontSize: "0.67rem",
    color: "#52525b",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  sbCount: {
    fontSize: "0.7rem",
    fontWeight: 600,
    color: "#71717a",
    flexShrink: 0,
  },
  sbBadge: {
    fontSize: "0.6rem",
    fontWeight: 600,
    background: "rgba(212, 168, 67, 0.2)",
    color: "#a5b4fc",
    padding: "1px 6px",
    borderRadius: "8px",
    flexShrink: 0,
    minWidth: "18px",
    textAlign: "center" as const,
  },
  sbBadgeWarn: {
    fontSize: "0.6rem",
    fontWeight: 600,
    background: "rgba(245, 158, 11, 0.2)",
    color: "#fbbf24",
    padding: "1px 6px",
    borderRadius: "8px",
    flexShrink: 0,
  },
  sbDivider: {
    height: "1px",
    background: "rgba(255, 255, 255, 0.06)",
    margin: "6px 14px",
  },
  sbAvatar: {
    width: "22px",
    height: "22px",
    borderRadius: "6px",
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    fontSize: "0.55rem",
    fontWeight: 700,
    color: "#fff",
    flexShrink: 0,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // EMAIL LIST (compact, div-based)
  // ═══════════════════════════════════════════════════════════════════════════════

  listSearch: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "10px 14px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.06)",
    background: "rgba(0, 0, 0, 0.1)",
  },
  listSearchInput: {
    background: "transparent",
    border: "none" as const,
    color: "#e2e8f0",
    fontSize: "0.8rem",
    outline: "none" as const,
    width: "100%",
  },
  emailItem: {
    display: "flex" as const,
    gap: "10px",
    padding: "10px 14px",
    cursor: "pointer" as const,
    borderBottom: "1px solid rgba(255, 255, 255, 0.04)",
  },
  emailItemHover: {
    background: "rgba(255, 255, 255, 0.03)",
  },
  emailItemSelected: {
    background: "rgba(212, 168, 67, 0.12)",
  },
  emailItemUnread: {
    background: "rgba(212, 168, 67, 0.05)",
  },
  emailItemBody: {
    flex: 1,
    minWidth: 0,
    display: "flex" as const,
    flexDirection: "column" as const,
    gap: "2px",
  },
  emailItemRow1: {
    display: "flex" as const,
    alignItems: "baseline" as const,
    justifyContent: "space-between" as const,
    gap: "8px",
  },
  emailItemFrom: {
    fontSize: "0.8rem",
    color: "#e2e8f0",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
    flex: 1,
    minWidth: 0,
  },
  emailItemDate: {
    fontSize: "0.7rem",
    color: "#71717a",
    flexShrink: 0,
    whiteSpace: "nowrap" as const,
  },
  emailItemSubject: {
    fontSize: "0.75rem",
    color: "#71717a",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  emailItemAiBadge: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "3px",
    padding: "1px 5px",
    borderRadius: "4px",
    fontSize: "0.6rem",
    fontWeight: 600,
    marginTop: "2px",
    width: "fit-content" as const,
  },
  emailItemCheckbox: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    width: "18px",
    flexShrink: 0,
    cursor: "pointer" as const,
    paddingTop: "2px",
  },
  emailItemChecked: {
    background: "rgba(212, 168, 67, 0.08)",
  },
  emailItemPreview: {
    fontSize: "0.7rem",
    color: "#52525b",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
    marginTop: "1px",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // TOOLBAR (Sort + Group + Count)
  // ═══════════════════════════════════════════════════════════════════════════════

  toolbarRow: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "6px 14px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.06)",
    background: "rgba(0, 0, 0, 0.15)",
    flexWrap: "wrap" as const,
  },
  toolbarSelect: {
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#a1a1aa",
    fontSize: "0.7rem",
    padding: "3px 6px",
    borderRadius: "5px",
    outline: "none" as const,
    cursor: "pointer" as const,
  },
  toolbarBtn: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    color: "#71717a",
    width: "24px",
    height: "24px",
    borderRadius: "5px",
    cursor: "pointer" as const,
    padding: 0,
  },
  toolbarBtnActive: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    background: "rgba(212, 168, 67, 0.15)",
    border: "1px solid rgba(212, 168, 67, 0.3)",
    color: "#a5b4fc",
    width: "24px",
    height: "24px",
    borderRadius: "5px",
    cursor: "pointer" as const,
    padding: 0,
  },
  toolbarCount: {
    fontSize: "0.7rem",
    color: "#52525b",
    marginLeft: "auto" as const,
    whiteSpace: "nowrap" as const,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // FILTER CHIPS
  // ═══════════════════════════════════════════════════════════════════════════════

  chipBar: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "4px",
    padding: "6px 14px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.06)",
    overflowX: "auto" as const,
    flexShrink: 0,
  },
  chip: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "4px",
    padding: "3px 8px",
    borderRadius: "12px",
    fontSize: "0.65rem",
    fontWeight: 500,
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    color: "#71717a",
    cursor: "pointer" as const,
    whiteSpace: "nowrap" as const,
    transition: "all 0.15s",
  },
  chipCount: {
    fontSize: "0.6rem",
    opacity: 0.7,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // BATCH TOOLBAR
  // ═══════════════════════════════════════════════════════════════════════════════

  batchBar: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    padding: "6px 14px",
    background: "rgba(212, 168, 67, 0.1)",
    borderBottom: "1px solid rgba(212, 168, 67, 0.2)",
  },
  batchCount: {
    fontSize: "0.75rem",
    color: "#a5b4fc",
    fontWeight: 600,
  },
  batchBtn: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "4px",
    background: "rgba(255, 255, 255, 0.05)",
    border: "1px solid rgba(255, 255, 255, 0.1)",
    color: "#a1a1aa",
    padding: "3px 8px",
    borderRadius: "5px",
    fontSize: "0.7rem",
    cursor: "pointer" as const,
  },
  batchBtnDanger: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    gap: "4px",
    background: "rgba(239, 68, 68, 0.1)",
    border: "1px solid rgba(239, 68, 68, 0.2)",
    color: "#f87171",
    padding: "3px 8px",
    borderRadius: "5px",
    fontSize: "0.7rem",
    cursor: "pointer" as const,
  },
  batchClose: {
    display: "flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    background: "transparent",
    border: "none" as const,
    color: "#71717a",
    cursor: "pointer" as const,
    padding: "2px",
    marginLeft: "4px",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // GROUP HEADERS
  // ═══════════════════════════════════════════════════════════════════════════════

  groupHeader: {
    display: "flex" as const,
    alignItems: "center" as const,
    gap: "8px",
    padding: "6px 14px",
    background: "rgba(0, 0, 0, 0.25)",
    borderBottom: "1px solid rgba(255, 255, 255, 0.06)",
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
  },
  groupLabel: {
    fontSize: "0.7rem",
    fontWeight: 600,
    color: "#a1a1aa",
    textTransform: "uppercase" as const,
    letterSpacing: "0.04em",
  },
  groupCount: {
    fontSize: "0.6rem",
    color: "#52525b",
    background: "rgba(255, 255, 255, 0.05)",
    padding: "1px 6px",
    borderRadius: "8px",
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // KEYBOARD HELP MODAL
  // ═══════════════════════════════════════════════════════════════════════════════

  kbdHelp: {
    position: "fixed" as const,
    bottom: "20px",
    right: "20px",
    background: "#1a1a2e",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    borderRadius: "12px",
    padding: "16px 20px",
    zIndex: 999,
    minWidth: "200px",
    boxShadow: "0 8px 32px rgba(0,0,0,0.5)",
  },
  kbdRow: {
    display: "flex" as const,
    justifyContent: "space-between" as const,
    padding: "3px 0",
    fontSize: "0.75rem",
  },
  kbdKey: {
    display: "inline-flex" as const,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    background: "rgba(255, 255, 255, 0.08)",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    borderRadius: "4px",
    padding: "1px 6px",
    fontSize: "0.7rem",
    fontFamily: "monospace",
    color: "#e2e8f0",
    minWidth: "20px",
  },
} as const;
