/**
 * NbResponsePage — NB-Antwort-Orchestrator UI mit Auto-Resolve
 * Zeigt offene NB-Rückfrage-Tasks, Complaints, Thread-Timeline,
 * Dokumenten-Checkliste, Anhang-Historie, Antwort-Vorschau
 */
import { useState, useEffect, useCallback, useRef } from "react";
import {
  Mail, FileText, Check, X, Clock, Send, RefreshCw,
  ChevronLeft, ChevronRight, AlertTriangle, CheckCircle2,
  Loader2, Bell, Eye, MessageSquare, Paperclip, ArrowDown,
  ArrowUp, Shield, Zap, HelpCircle, PenTool, Upload,
  Settings, Pen, Trash2, Undo2, Activity, Plus, XCircle,
  Search, MailCheck, FileWarning, UserCheck
} from "lucide-react";
import { apiGet, apiPost, apiPut } from "../api/client";
import { useAuth } from "../pages/AuthContext";
import "./nb-response.css";

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

interface NbComplaint {
  id: number;
  taskId: number;
  type: string;
  description: string;
  extractedDetail: any;
  resolved: boolean;
  resolveMethod: string | null;
  resolveDetail: string | null;
  resolvedAt: string | null;
  createdAt: string;
}

interface NbTask {
  id: number;
  installationId: number;
  triggerEmailId: number;
  status: string;
  requiredDocuments: DocRequirement[] | null;
  nbSummary: string | null;
  nbDeadline: string | null;
  vdeFormularSetId: number | null;
  vdeAutoGenerated: boolean;
  customerNotifiedAt: string | null;
  approvedAt: string | null;
  responseTo: string | null;
  responseSubject: string | null;
  responseBody: string | null;
  attachedDocumentIds: number[] | null;
  sentAt: string | null;
  errorMessage: string | null;
  resolveStatus: string | null;
  threadEmails: ThreadEmail[] | null;
  complaints: NbComplaint[];
  createdAt: string;
  updatedAt: string;
  installation: {
    id: number;
    publicId: string;
    customerName: string | null;
    gridOperator: string | null;
    status: string;
    netzbetreiberId: number | null;
  };
}

interface DocRequirement {
  name: string;
  type: string;
  present: boolean;
  source: "customer" | "system" | "vde";
}

interface TriggerEmail {
  id: number;
  subject: string | null;
  bodyText: string | null;
  bodyHtml: string | null;
  fromAddress: string | null;
  receivedAt: string;
  attachments: string | null;
}

interface ThreadEmail {
  id: number;
  direction: "INBOUND" | "OUTBOUND";
  fromAddress: string;
  toAddress?: string;
  subject: string | null;
  bodyText: string | null;
  date: string;
  source: string;
  attachments: Array<{
    id: number;
    fileName: string;
    mimeType: string;
    fileSize: number;
    documentType: string | null;
    isFromNb: boolean;
  }>;
  isTrigger?: boolean;
}

interface NbTaskComment {
  id: number;
  taskId: number;
  type: "SYSTEM" | "MANUAL";
  action: string;
  message: string;
  metadata: any;
  authorId: number | null;
  authorName: string | null;
  createdAt: string;
}

interface AttachmentRecord {
  id: number;
  fileName: string;
  mimeType: string;
  fileSize: number;
  documentType: string | null;
  isFromNb: boolean;
  createdAt: string;
}

interface TaskDetail {
  task: NbTask & {
    installation: NbTask["installation"] & {
      contactEmail: string | null;
      netzbetreiberId: number | null;
      documents: Array<{
        id: number;
        kategorie: string;
        originalName: string;
        dateiname: string;
        dateigroesse: number | null;
        createdAt: string;
      }>;
    };
  };
  triggerEmail: TriggerEmail | null;
  attachmentHistory: AttachmentRecord[];
  comments: NbTaskComment[];
}

const STATUS_LABELS: Record<string, { label: string; color: string }> = {
  ANALYZING: { label: "Analysiert...", color: "#EAD068" },
  COLLECTING: { label: "Sammelt Dokumente", color: "#F97316" },
  READY_FOR_REVIEW: { label: "Bereit", color: "#22C55E" },
  APPROVED: { label: "Freigegeben", color: "#3B82F6" },
  SENT: { label: "Gesendet", color: "#34d399" },
  CANCELLED: { label: "Abgebrochen", color: "#71717a" },
};

const RESOLVE_STATUS_LABELS: Record<string, { label: string; color: string }> = {
  resolved: { label: "Gelöst", color: "#22C55E" },
  partial: { label: "Teilweise", color: "#F97316" },
  manual_needed: { label: "Manuell", color: "#ef4444" },
  pending: { label: "Ausstehend", color: "#71717a" },
};

const COMPLAINT_TYPE_INFO: Record<string, { label: string; icon: any; color: string }> = {
  MISSING_SIGNATURE: { label: "Unterschrift fehlt", icon: PenTool, color: "#F97316" },
  SCHALTPLAN_ERROR: { label: "Schaltplan-Fehler", icon: Zap, color: "#ef4444" },
  WRONG_DATE: { label: "Falsches Datum", icon: Clock, color: "#F97316" },
  MISSING_DOCUMENT: { label: "Dokument fehlt", icon: FileText, color: "#ef4444" },
  FORM_INCOMPLETE: { label: "Formular unvollständig", icon: AlertTriangle, color: "#F97316" },
  CLARIFICATION_NEEDED: { label: "Klärung nötig", icon: HelpCircle, color: "#EAD068" },
};

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════════════════

export default function NbResponsePage() {
  const { user } = useAuth();
  const isAdmin = user?.role === "ADMIN";

  const [tasks, setTasks] = useState<NbTask[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [statusFilter, setStatusFilter] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<Record<string, number>>({});
  const [selectedTaskId, setSelectedTaskId] = useState<number | null>(null);
  const [detail, setDetail] = useState<TaskDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [toast, setToast] = useState<{ msg: string; type: "success" | "error" } | null>(null);
  const [showSignatureModal, setShowSignatureModal] = useState(false);

  const loadTasks = useCallback(async () => {
    setLoading(true);
    try {
      const params: Record<string, string | number> = { page, limit: 20 };
      if (statusFilter) params.status = statusFilter;
      const data = await apiGet<{
        tasks: NbTask[];
        total: number;
        stats: Record<string, number>;
      }>("/api/nb-response/tasks?" + new URLSearchParams(params as Record<string, string>));
      setTasks(data.tasks);
      setTotal(data.total);
      setStats(data.stats);
    } catch {
      showToast("Fehler beim Laden", "error");
    }
    setLoading(false);
  }, [page, statusFilter]);

  useEffect(() => { loadTasks(); }, [loadTasks]);

  const loadDetail = async (taskId: number) => {
    setSelectedTaskId(taskId);
    setDetailLoading(true);
    try {
      const data = await apiGet<TaskDetail>(`/api/nb-response/tasks/${taskId}`);
      setDetail(data);
    } catch {
      setDetail(null);
    }
    setDetailLoading(false);
  };

  const showToast = (msg: string, type: "success" | "error" = "success") => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3000);
  };

  const handleApprove = async () => {
    if (!detail || !isAdmin) return;
    const confirmed = window.confirm(
      `NB-Antwort wirklich senden?\n\nAn: ${detail.task.responseTo || "(kein Empfänger)"}\nBetreff: ${detail.task.responseSubject || "—"}\n\nDiese Aktion kann nicht rückgängig gemacht werden.`
    );
    if (!confirmed) return;
    try {
      await apiPost(`/api/nb-response/tasks/${detail.task.id}/approve`, {
        body: detail.task.responseBody,
        subject: detail.task.responseSubject,
      });
      showToast("NB-Antwort gesendet!");
      loadTasks();
      loadDetail(detail.task.id);
    } catch {
      showToast("Senden fehlgeschlagen", "error");
    }
  };

  const handleCancel = async () => {
    if (!detail || !isAdmin) return;
    if (!window.confirm("Task wirklich abbrechen?")) return;
    try {
      await apiPost(`/api/nb-response/tasks/${detail.task.id}/cancel`, {});
      showToast("Task abgebrochen");
      loadTasks();
      loadDetail(detail.task.id);
    } catch {
      showToast("Abbrechen fehlgeschlagen", "error");
    }
  };

  const handleRefresh = async () => {
    if (!detail) return;
    try {
      await apiPost(`/api/nb-response/tasks/${detail.task.id}/refresh`, {});
      showToast("Aktualisiert");
      loadDetail(detail.task.id);
    } catch {
      showToast("Fehler", "error");
    }
  };

  const handleReResolve = async () => {
    if (!detail || !isAdmin) return;
    try {
      await apiPost(`/api/nb-response/tasks/${detail.task.id}/re-resolve`, {});
      showToast("Re-Analyse gestartet");
      loadDetail(detail.task.id);
    } catch {
      showToast("Re-Analyse fehlgeschlagen", "error");
    }
  };

  const handleRequestCustomer = async () => {
    if (!detail || !isAdmin) return;
    try {
      await apiPost(`/api/nb-response/tasks/${detail.task.id}/request-customer`, {});
      showToast("Kunde benachrichtigt");
      loadDetail(detail.task.id);
    } catch {
      showToast("Fehler", "error");
    }
  };

  const handleResponseEdit = async (body: string) => {
    if (!detail) return;
    try {
      await apiPut(`/api/nb-response/tasks/${detail.task.id}/response`, { body });
      setDetail((prev) => prev ? { ...prev, task: { ...prev.task, responseBody: body } } : null);
    } catch {
      showToast("Speichern fehlgeschlagen", "error");
    }
  };

  const pages = Math.ceil(total / 20);

  return (
    <div className="nbr-container">
      {/* Header */}
      <div className="nbr-header">
        <h1><Mail size={22} /> NB-Antworten</h1>
        <div className="nbr-stats-badges">
          <StatBadge label="Offen" count={stats.COLLECTING || 0} color="#F97316" />
          <StatBadge label="Bereit" count={stats.READY_FOR_REVIEW || 0} color="#22C55E" />
          <StatBadge label="Gesendet" count={stats.SENT || 0} color="#34d399" />
          {isAdmin && (
            <button
              className="nbr-btn"
              style={{ marginLeft: 8 }}
              onClick={() => setShowSignatureModal(true)}
              title="EFK-Signaturen verwalten"
            >
              <Settings size={14} /> EFK-Signatur
            </button>
          )}
        </div>
      </div>

      {/* Filter */}
      <div className="nbr-toolbar">
        <div className="nbr-filter-chips">
          <button className={`nbr-chip ${!statusFilter ? "active" : ""}`} onClick={() => { setStatusFilter(""); setPage(1); }}>Alle</button>
          <button className={`nbr-chip ${statusFilter === "COLLECTING" ? "active" : ""}`} onClick={() => { setStatusFilter("COLLECTING"); setPage(1); }}>Sammelt</button>
          <button className={`nbr-chip ${statusFilter === "READY_FOR_REVIEW" ? "active" : ""}`} onClick={() => { setStatusFilter("READY_FOR_REVIEW"); setPage(1); }}>Bereit</button>
          <button className={`nbr-chip ${statusFilter === "SENT" ? "active" : ""}`} onClick={() => { setStatusFilter("SENT"); setPage(1); }}>Gesendet</button>
        </div>
        <button className="nbr-btn" onClick={loadTasks}><RefreshCw size={12} /> Aktualisieren</button>
      </div>

      {/* Content */}
      {loading ? (
        <div className="nbr-loading"><Loader2 size={16} className="nbr-spin" /> Laden...</div>
      ) : tasks.length === 0 ? (
        <div className="nbr-empty">Keine NB-Response-Tasks vorhanden</div>
      ) : (
        <div className="nbr-content">
          <div className="nbr-table-wrap">
            <table className="nbr-table">
              <thead>
                <tr>
                  <th>Installation</th>
                  <th>Netzbetreiber</th>
                  <th>Status</th>
                  <th>Resolve</th>
                  <th>Dokumente</th>
                  <th>Erstellt</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {tasks.map((t) => {
                  const docs = t.requiredDocuments || [];
                  const present = docs.filter((d) => d.present).length;
                  return (
                    <tr
                      key={t.id}
                      className={selectedTaskId === t.id ? "selected" : ""}
                      onClick={() => loadDetail(t.id)}
                    >
                      <td>
                        <div className="nbr-cell-name">{t.installation.customerName || t.installation.publicId}</div>
                        <div className="nbr-cell-sub">{t.installation.publicId}</div>
                      </td>
                      <td className="nbr-cell-sub">{t.installation.gridOperator || "—"}</td>
                      <td><StatusBadge status={t.status} /></td>
                      <td>{t.resolveStatus && <ResolveBadge status={t.resolveStatus} />}</td>
                      <td>
                        <span className={`nbr-doc-count ${present === docs.length && docs.length > 0 ? "complete" : ""}`}>
                          {present}/{docs.length}
                        </span>
                      </td>
                      <td className="nbr-cell-sub">{timeAgo(t.createdAt)}</td>
                      <td><Eye size={14} style={{ color: "#52525b" }} /></td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
            {pages > 1 && (
              <div className="nbr-pagination">
                <span>{total} Tasks</span>
                <div className="nbr-page-btns">
                  <button disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={14} /></button>
                  <span>{page} / {pages}</span>
                  <button disabled={page >= pages} onClick={() => setPage(page + 1)}><ChevronRight size={14} /></button>
                </div>
              </div>
            )}
          </div>

          {/* Detail Panel */}
          {(selectedTaskId || detailLoading) && (
            <DetailPanel
              detail={detail}
              loading={detailLoading}
              isAdmin={isAdmin}
              onClose={() => { setSelectedTaskId(null); setDetail(null); }}
              onApprove={handleApprove}
              onCancel={handleCancel}
              onRefresh={handleRefresh}
              onReResolve={handleReResolve}
              onRequestCustomer={handleRequestCustomer}
              onResponseEdit={handleResponseEdit}
              onReloadDetail={() => selectedTaskId && loadDetail(selectedTaskId)}
              showToast={showToast}
            />
          )}
        </div>
      )}

      {/* Signature Modal */}
      {showSignatureModal && (
        <SignatureModal onClose={() => setShowSignatureModal(false)} showToast={showToast} />
      )}

      {toast && <div className={`nbr-toast nbr-toast-${toast.type}`}>{toast.msg}</div>}
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// DETAIL PANEL
// ═══════════════════════════════════════════════════════════════════════════════

function DetailPanel({
  detail,
  loading,
  isAdmin,
  onClose,
  onApprove,
  onCancel,
  onRefresh,
  onReResolve,
  onRequestCustomer,
  onResponseEdit,
  onReloadDetail,
  showToast,
}: {
  detail: TaskDetail | null;
  loading: boolean;
  isAdmin: boolean;
  onClose: () => void;
  onApprove: () => void;
  onCancel: () => void;
  onRefresh: () => void;
  onReResolve: () => void;
  onRequestCustomer: () => void;
  onResponseEdit: (body: string) => void;
  onReloadDetail: () => void;
  showToast: (msg: string, type: "success" | "error") => void;
}) {
  const [editingBody, setEditingBody] = useState(false);
  const [bodyDraft, setBodyDraft] = useState("");

  useEffect(() => {
    if (detail?.task.responseBody) {
      setBodyDraft(detail.task.responseBody);
    }
  }, [detail?.task.responseBody]);

  if (loading) {
    return (
      <div className="nbr-detail-overlay" onClick={onClose}>
        <div className="nbr-detail-panel" onClick={(e) => e.stopPropagation()}>
          <div className="nbr-loading"><Loader2 size={16} className="nbr-spin" /> Laden...</div>
        </div>
      </div>
    );
  }

  if (!detail) return null;

  const { task, triggerEmail, attachmentHistory } = detail;
  const docs = task.requiredDocuments || [];
  const isNoReply = !task.responseTo;
  const complaints = task.complaints || [];
  const threadEmails = task.threadEmails || [];

  return (
    <div className="nbr-detail-overlay" onClick={onClose}>
      <div className="nbr-detail-panel" onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className="nbr-detail-header">
          <div>
            <h3>NB-Rückfrage: {task.installation.gridOperator || "NB"}</h3>
            <div className="nbr-detail-sub">
              {task.installation.customerName || task.installation.publicId}
              <StatusBadge status={task.status} />
              {task.resolveStatus && <ResolveBadge status={task.resolveStatus} />}
            </div>
          </div>
          <button className="nbr-close" onClick={onClose}><X size={18} /></button>
        </div>

        <div className="nbr-detail-body">
          {/* noreply@ Warnung */}
          {isNoReply && task.status !== "CANCELLED" && task.status !== "SENT" && (
            <div className="nbr-noreply-warning">
              <AlertTriangle size={16} />
              <span>
                <strong>Kein Empfänger!</strong> Die Trigger-Email kam von einer noreply@-Adresse.
                Bitte Empfänger manuell setzen bevor gesendet wird.
              </span>
            </div>
          )}

          {/* Original-Email */}
          {triggerEmail && (
            <EmailSection triggerEmail={triggerEmail} />
          )}

          {/* NB-Zusammenfassung */}
          {task.nbSummary && (
            <div className="nbr-summary-box">
              <AlertTriangle size={14} /> {task.nbSummary}
              {task.nbDeadline && (
                <span className="nbr-deadline">
                  <Clock size={12} /> Frist: {new Date(task.nbDeadline).toLocaleDateString("de-DE")}
                </span>
              )}
            </div>
          )}

          {/* Beschwerdepunkte */}
          {complaints.length > 0 && (
            <CollapsibleSection title={`Beschwerdepunkte (${complaints.length})`} defaultOpen>
              <div className="nbr-complaints-list">
                {complaints.map((c) => {
                  const info = COMPLAINT_TYPE_INFO[c.type] || { label: c.type, icon: HelpCircle, color: "#71717a" };
                  const Icon = info.icon;
                  return (
                    <div key={c.id} className={`nbr-complaint-item ${c.resolved ? "resolved" : "open"}`}>
                      <div className="nbr-complaint-header">
                        <Icon size={14} style={{ color: info.color, flexShrink: 0 }} />
                        <span className="nbr-complaint-type" style={{ color: info.color }}>{info.label}</span>
                        {c.resolved ? (
                          <span className="nbr-complaint-badge resolved"><CheckCircle2 size={10} /> Gelöst</span>
                        ) : (
                          <span className="nbr-complaint-badge open"><X size={10} /> Offen</span>
                        )}
                      </div>
                      <div className="nbr-complaint-desc">{c.description}</div>
                      {c.resolved && c.resolveDetail && (
                        <div className="nbr-complaint-resolve">
                          <CheckCircle2 size={12} /> {c.resolveDetail}
                        </div>
                      )}
                      {!c.resolved && c.resolveDetail && (
                        <div className="nbr-complaint-action">
                          <AlertTriangle size={12} /> {c.resolveDetail}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
              {isAdmin && !["SENT", "CANCELLED"].includes(task.status) && (
                <button className="nbr-btn nbr-btn-sm" style={{ marginTop: 8 }} onClick={onReResolve}>
                  <RefreshCw size={12} /> Re-Analyse
                </button>
              )}
            </CollapsibleSection>
          )}

          {/* Email-Verlauf (Thread) */}
          {threadEmails.length > 0 && (
            <CollapsibleSection title={`Email-Verlauf (${threadEmails.length})`}>
              <div className="nbr-thread-timeline">
                {threadEmails.map((e, i) => (
                  <div key={`${e.source}_${e.id}_${i}`} className={`nbr-thread-item ${e.direction === "INBOUND" ? "inbound" : "outbound"} ${e.isTrigger ? "trigger" : ""}`}>
                    <div className="nbr-thread-icon">
                      {e.direction === "INBOUND" ? <ArrowDown size={12} /> : <ArrowUp size={12} />}
                    </div>
                    <div className="nbr-thread-content">
                      <div className="nbr-thread-meta">
                        <span className="nbr-thread-from">{e.fromAddress}</span>
                        <span className="nbr-thread-date">{new Date(e.date).toLocaleString("de-DE")}</span>
                        {e.isTrigger && <span className="nbr-trigger-badge">Trigger</span>}
                      </div>
                      <div className="nbr-thread-subject">{e.subject || "(kein Betreff)"}</div>
                      {e.attachments && e.attachments.length > 0 && (
                        <div className="nbr-thread-attachments">
                          <Paperclip size={10} /> {e.attachments.map(a => a.fileName).join(", ")}
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </CollapsibleSection>
          )}

          {/* Dokumenten-Checkliste */}
          <CollapsibleSection title={`Dokumenten-Checkliste (${docs.filter((d) => d.present).length}/${docs.length})`} defaultOpen>
            {docs.length === 0 ? (
              <div className="nbr-empty-small">Keine Anforderungen</div>
            ) : (
              <div className="nbr-doc-list">
                {docs.map((d, i) => (
                  <div key={i} className={`nbr-doc-item ${d.present ? "present" : "missing"}`}>
                    {d.present ? <CheckCircle2 size={14} /> : d.source === "vde" ? <Loader2 size={14} /> : <X size={14} />}
                    <span className="nbr-doc-name">{d.name}</span>
                    <span className="nbr-doc-status">
                      {d.present ? "vorhanden" : d.source === "vde" ? "wird generiert" : "fehlt"}
                    </span>
                  </div>
                ))}
              </div>
            )}
          </CollapsibleSection>

          {/* Vorhandene Dokumente */}
          {task.installation.documents && task.installation.documents.length > 0 && (
            <CollapsibleSection title={`Vorhandene Dokumente (${task.installation.documents.length})`}>
              <div className="nbr-doc-list">
                {task.installation.documents.map((d) => (
                  <div key={d.id} className="nbr-doc-item present">
                    <FileText size={14} />
                    <span className="nbr-doc-name">{d.originalName || d.dateiname}</span>
                    <span className="nbr-doc-status">{d.kategorie}</span>
                  </div>
                ))}
              </div>
            </CollapsibleSection>
          )}

          {/* Anhang-Historie */}
          {attachmentHistory && attachmentHistory.length > 0 && (
            <CollapsibleSection title={`Anhang-Historie (${attachmentHistory.length})`}>
              <div className="nbr-attachment-history">
                {groupAttachmentsByType(attachmentHistory).map(([type, atts]) => (
                  <div key={type} className="nbr-att-group">
                    <div className="nbr-att-group-label">{type || "Unklassifiziert"}</div>
                    {atts.map((a) => (
                      <div key={a.id} className={`nbr-att-item ${a.isFromNb ? "from-nb" : ""}`}>
                        <Paperclip size={12} />
                        <span className="nbr-att-name">{a.fileName}</span>
                        <span className="nbr-att-meta">
                          {formatFileSize(a.fileSize)} · {a.isFromNb ? "von NB" : "gesendet"} · {new Date(a.createdAt).toLocaleDateString("de-DE")}
                        </span>
                      </div>
                    ))}
                  </div>
                ))}
              </div>
            </CollapsibleSection>
          )}

          {/* Antwort-Vorschau */}
          {task.responseBody && (
            <CollapsibleSection title="Antwort-Vorschau" defaultOpen>
              <div className="nbr-response-meta">
                <span>An: {task.responseTo || "—"}</span>
                <span>Betreff: {task.responseSubject || "—"}</span>
              </div>
              {editingBody ? (
                <div>
                  <textarea
                    className="nbr-response-textarea"
                    value={bodyDraft}
                    onChange={(e) => setBodyDraft(e.target.value)}
                    rows={10}
                  />
                  <div className="nbr-response-actions">
                    <button className="nbr-btn" onClick={() => setEditingBody(false)}>Abbrechen</button>
                    <button className="nbr-btn nbr-btn-primary" onClick={() => { onResponseEdit(bodyDraft); setEditingBody(false); }}>
                      Speichern
                    </button>
                  </div>
                </div>
              ) : (
                <div className="nbr-response-body" onClick={() => isAdmin && setEditingBody(true)}>
                  {task.responseBody}
                  {isAdmin && <span className="nbr-edit-hint">(Klicken zum Bearbeiten)</span>}
                </div>
              )}
              {task.attachedDocumentIds && task.attachedDocumentIds.length > 0 && (
                <div className="nbr-response-attachments">
                  Anhänge: {task.attachedDocumentIds.length} Dokumente
                </div>
              )}
            </CollapsibleSection>
          )}

          {/* Aktivität */}
          <ActivityTimeline
            comments={detail.comments || []}
            taskId={task.id}
            isAdmin={isAdmin}
            showToast={showToast}
            onCommentAdded={onReloadDetail}
          />

          {/* Kunden-Unterschrift (wenn VDE-FormularSet vorhanden) */}
          {isAdmin && task.vdeFormularSetId && !["SENT", "CANCELLED"].includes(task.status) && (
            <CollapsibleSection title="Kunden-Unterschrift">
              <CustomerSignatureSection
                vdeFormularSetId={task.vdeFormularSetId}
                showToast={showToast}
              />
            </CollapsibleSection>
          )}

          {/* Fehler */}
          {task.errorMessage && (
            <div className="nbr-error-box">
              <AlertTriangle size={14} /> {task.errorMessage}
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="nbr-detail-footer">
          {isAdmin && task.status === "COLLECTING" && (
            <button className="nbr-btn" onClick={onRequestCustomer}>
              <Bell size={14} /> Kunde erinnern
            </button>
          )}
          {isAdmin && !["SENT", "CANCELLED"].includes(task.status) && (
            <button className="nbr-btn" style={{ color: "#f87171" }} onClick={onCancel}>
              <X size={14} /> Abbrechen
            </button>
          )}
          <button className="nbr-btn" onClick={onRefresh}>
            <RefreshCw size={14} /> Aktualisieren
          </button>
          {isAdmin && task.status === "READY_FOR_REVIEW" && !isNoReply && (
            <button className="nbr-btn nbr-btn-send" onClick={onApprove}>
              <Send size={14} /> Freigeben & Senden
            </button>
          )}
          {isAdmin && task.status === "READY_FOR_REVIEW" && isNoReply && (
            <span style={{ color: "#f87171", fontSize: 12, display: "flex", alignItems: "center", gap: 4 }}>
              <AlertTriangle size={12} /> Senden blockiert — kein Empfänger
            </span>
          )}
          {task.status === "SENT" && (
            <span className="nbr-sent-info">
              <Check size={14} /> Gesendet am {task.sentAt ? new Date(task.sentAt).toLocaleString("de-DE") : "—"}
            </span>
          )}
          {task.status === "CANCELLED" && (
            <span style={{ color: "#71717a", fontSize: 12 }}>Task abgebrochen</span>
          )}
        </div>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// EMAIL SECTION (Original-Email mit HTML/Text-Toggle)
// ═══════════════════════════════════════════════════════════════════════════════

function EmailSection({ triggerEmail }: { triggerEmail: TriggerEmail }) {
  const [showHtml, setShowHtml] = useState(!!triggerEmail.bodyHtml);

  return (
    <CollapsibleSection title="Original-Email" defaultOpen>
      <div className="nbr-email-meta">
        <span>Von: {triggerEmail.fromAddress}</span>
        <span>Betreff: {triggerEmail.subject || "—"}</span>
        <span>Empfangen: {new Date(triggerEmail.receivedAt).toLocaleString("de-DE")}</span>
      </div>
      {triggerEmail.bodyHtml && triggerEmail.bodyText && (
        <div className="nbr-email-toggle">
          <button
            className={`nbr-chip ${showHtml ? "active" : ""}`}
            onClick={() => setShowHtml(true)}
          >HTML</button>
          <button
            className={`nbr-chip ${!showHtml ? "active" : ""}`}
            onClick={() => setShowHtml(false)}
          >Text</button>
        </div>
      )}
      {showHtml && triggerEmail.bodyHtml ? (
        <div
          className="nbr-email-html"
          dangerouslySetInnerHTML={{ __html: sanitizeEmailHtml(triggerEmail.bodyHtml) }}
        />
      ) : (
        <div className="nbr-email-body">
          {triggerEmail.bodyText || "(kein Text)"}
        </div>
      )}
    </CollapsibleSection>
  );
}

function sanitizeEmailHtml(html: string): string {
  // Script-Tags, Event-Handler und externe Ressourcen entfernen
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, "")
    .replace(/on\w+="[^"]*"/gi, "")
    .replace(/on\w+='[^']*'/gi, "")
    .replace(/<style[\s\S]*?<\/style>/gi, "")
    .replace(/javascript:/gi, "");
}

// ═══════════════════════════════════════════════════════════════════════════════
// ACTIVITY TIMELINE
// ═══════════════════════════════════════════════════════════════════════════════

const ACTION_META: Record<string, { label: string; icon: any; color: string }> = {
  TASK_CREATED: { label: "Task erstellt", icon: Plus, color: "#3B82F6" },
  TASK_UPDATED: { label: "Task aktualisiert", icon: RefreshCw, color: "#F97316" },
  ATTACHMENTS_PROCESSED: { label: "Anhänge verarbeitet", icon: Paperclip, color: "#D4A843" },
  THREAD_ANALYZED: { label: "Thread analysiert", icon: Mail, color: "#D4A843" },
  COMPLAINTS_PARSED: { label: "Complaints geparst", icon: Search, color: "#F97316" },
  RESOLVE_COMPLETED: { label: "Auto-Resolve", icon: Zap, color: "#22C55E" },
  DOCUMENT_GAP_ASSESSED: { label: "Dokument-Check", icon: FileText, color: "#D4A843" },
  VDE_AUTO_CREATED: { label: "VDE-Set erstellt", icon: FileText, color: "#3B82F6" },
  CUSTOMER_NOTIFIED: { label: "Kunde benachrichtigt", icon: Bell, color: "#F97316" },
  RESPONSE_DRAFTED: { label: "Entwurf erstellt", icon: Mail, color: "#22C55E" },
  RESPONSE_EDITED: { label: "Antwort bearbeitet", icon: Pen, color: "#EAD068" },
  RE_RESOLVE_TRIGGERED: { label: "Re-Analyse", icon: RefreshCw, color: "#F97316" },
  APPROVED_AND_SENT: { label: "Gesendet", icon: MailCheck, color: "#22C55E" },
  SEND_FAILED: { label: "Senden fehlgeschlagen", icon: XCircle, color: "#ef4444" },
  TASK_CANCELLED: { label: "Abgebrochen", icon: X, color: "#71717a" },
  STATUS_CHANGED: { label: "Status geändert", icon: Activity, color: "#D4A843" },
  IBN_CHECKLIST_CREATED: { label: "IBN-Checkliste", icon: CheckCircle2, color: "#3B82F6" },
  NOREPLY_WARNING: { label: "noreply@ Warnung", icon: AlertTriangle, color: "#ef4444" },
  PDF_ANALYZED: { label: "PDF analysiert", icon: FileText, color: "#D4A843" },
  NB_PATTERNS_APPLIED: { label: "NB-Muster", icon: Shield, color: "#EAD068" },
  SCHALTPLAN_AI_CORRECTED: { label: "Schaltplan korrigiert", icon: Zap, color: "#22C55E" },
  ADMIN_COMMENT: { label: "Kommentar", icon: MessageSquare, color: "#a855f7" },
};

function ActivityTimeline({
  comments,
  taskId,
  isAdmin,
  showToast,
  onCommentAdded,
}: {
  comments: NbTaskComment[];
  taskId: number;
  isAdmin: boolean;
  showToast: (msg: string, type: "success" | "error") => void;
  onCommentAdded: () => void;
}) {
  const [newComment, setNewComment] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async () => {
    if (!newComment.trim() || submitting) return;
    setSubmitting(true);
    try {
      await apiPost(`/api/nb-response/tasks/${taskId}/comments`, { message: newComment.trim() });
      setNewComment("");
      onCommentAdded();
    } catch {
      showToast("Kommentar fehlgeschlagen", "error");
    }
    setSubmitting(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      handleSubmit();
    }
  };

  return (
    <CollapsibleSection title={`Aktivität (${comments.length})`} defaultOpen>
      <div className="nbr-activity-timeline">
        {comments.length === 0 ? (
          <div className="nbr-empty-small">Noch keine Aktivität</div>
        ) : (
          comments.map((c, i) => {
            const meta = ACTION_META[c.action] || { label: c.action, icon: Activity, color: "#71717a" };
            const Icon = meta.icon;
            const isManual = c.type === "MANUAL";
            return (
              <div key={c.id} className={`nbr-activity-item ${isManual ? "manual" : "system"}`}>
                {i < comments.length - 1 && <div className="nbr-activity-line" />}
                <div className="nbr-activity-dot" style={{ borderColor: meta.color, background: isManual ? `${meta.color}20` : "#18181b" }}>
                  <Icon size={10} style={{ color: meta.color }} />
                </div>
                <div className="nbr-activity-content">
                  <div className="nbr-activity-header">
                    <span className="nbr-activity-label" style={{ color: meta.color }}>{meta.label}</span>
                    <span className="nbr-activity-time">{formatActivityTime(c.createdAt)}</span>
                  </div>
                  <div className={`nbr-activity-message ${isManual ? "manual" : ""}`}>
                    {c.message}
                  </div>
                  {isManual && c.authorName && (
                    <div className="nbr-activity-author">— {c.authorName}</div>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>

      {/* Admin-Kommentar Eingabe */}
      {isAdmin && (
        <div className="nbr-activity-input">
          <textarea
            className="nbr-activity-textarea"
            placeholder="Kommentar hinzufügen... (Ctrl+Enter zum Senden)"
            value={newComment}
            onChange={(e) => setNewComment(e.target.value)}
            onKeyDown={handleKeyDown}
            rows={2}
          />
          <button
            className="nbr-btn nbr-btn-primary nbr-btn-sm"
            onClick={handleSubmit}
            disabled={!newComment.trim() || submitting}
          >
            {submitting ? <Loader2 size={12} className="nbr-spin" /> : <Send size={12} />} Senden
          </button>
        </div>
      )}
    </CollapsibleSection>
  );
}

function formatActivityTime(dateStr: string): string {
  const d = new Date(dateStr);
  const now = Date.now();
  const diff = now - d.getTime();
  if (diff < 60000) return "gerade eben";
  if (diff < 3600000) return `vor ${Math.floor(diff / 60000)}m`;
  if (diff < 86400000) return `vor ${Math.floor(diff / 3600000)}h`;
  return d.toLocaleString("de-DE", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" });
}

// ═══════════════════════════════════════════════════════════════════════════════
// SIGNATURE MODAL
// ═══════════════════════════════════════════════════════════════════════════════

interface EfkSig {
  id: number;
  efkName: string;
  efkBetrieb: string | null;
  efkEintragNr: string | null;
  signatureMime: string;
  isDefault: boolean;
  createdAt: string;
}

function SignatureModal({ onClose, showToast }: { onClose: () => void; showToast: (msg: string, type: "success" | "error") => void }) {
  const [signatures, setSignatures] = useState<EfkSig[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [inputMode, setInputMode] = useState<"draw" | "upload">("draw");
  const [formData, setFormData] = useState({ efkName: "", efkBetrieb: "", efkEintragNr: "", isDefault: true });
  const [file, setFile] = useState<File | null>(null);
  const [drawnSignature, setDrawnSignature] = useState<string | null>(null);

  const loadSignatures = async () => {
    try {
      const data = await apiGet<EfkSig[]>("/api/signatures");
      setSignatures(data);
    } catch { /* ignore */ }
    setLoading(false);
  };

  useEffect(() => { loadSignatures(); }, []);

  const handleSaveDrawn = async () => {
    if (!drawnSignature || !formData.efkName) return;
    setSaving(true);
    try {
      await apiPost("/api/signatures/draw", {
        signatureBase64: drawnSignature,
        efkName: formData.efkName,
        efkBetrieb: formData.efkBetrieb || undefined,
        efkEintragNr: formData.efkEintragNr || undefined,
        isDefault: formData.isDefault,
      });
      showToast("Signatur gespeichert", "success");
      setShowForm(false);
      setDrawnSignature(null);
      setFormData({ efkName: "", efkBetrieb: "", efkEintragNr: "", isDefault: true });
      loadSignatures();
    } catch {
      showToast("Speichern fehlgeschlagen", "error");
    }
    setSaving(false);
  };

  const handleUpload = async () => {
    if (!file || !formData.efkName) return;
    setSaving(true);
    try {
      const fd = new FormData();
      fd.append("signature", file);
      fd.append("efkName", formData.efkName);
      if (formData.efkBetrieb) fd.append("efkBetrieb", formData.efkBetrieb);
      if (formData.efkEintragNr) fd.append("efkEintragNr", formData.efkEintragNr);
      fd.append("isDefault", String(formData.isDefault));

      await fetch("/api/signatures", {
        method: "POST",
        headers: { Authorization: `Bearer ${localStorage.getItem("token")}` },
        body: fd,
      });
      showToast("Signatur hochgeladen", "success");
      setShowForm(false);
      setFile(null);
      setFormData({ efkName: "", efkBetrieb: "", efkEintragNr: "", isDefault: true });
      loadSignatures();
    } catch {
      showToast("Upload fehlgeschlagen", "error");
    }
    setSaving(false);
  };

  const handleSetDefault = async (id: number) => {
    try {
      await apiPut(`/api/signatures/${id}/default`, {});
      showToast("Standard-Signatur gesetzt", "success");
      loadSignatures();
    } catch {
      showToast("Fehler", "error");
    }
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm("Signatur wirklich löschen?")) return;
    try {
      await fetch(`/api/signatures/${id}`, {
        method: "DELETE",
        headers: { Authorization: `Bearer ${localStorage.getItem("token")}` },
      });
      showToast("Signatur gelöscht", "success");
      loadSignatures();
    } catch {
      showToast("Fehler", "error");
    }
  };

  return (
    <div className="nbr-detail-overlay" onClick={onClose}>
      <div className="nbr-modal" onClick={(e) => e.stopPropagation()} style={{ maxWidth: 560 }}>
        <div className="nbr-detail-header">
          <h3><PenTool size={16} /> EFK-Signaturen</h3>
          <button className="nbr-close" onClick={onClose}><X size={18} /></button>
        </div>

        <div className="nbr-detail-body" style={{ padding: 16 }}>
          {loading ? (
            <div className="nbr-loading"><Loader2 size={16} className="nbr-spin" /></div>
          ) : (
            <>
              {/* Bestehende Signaturen */}
              {signatures.length === 0 && !showForm && (
                <div className="nbr-empty-small">Keine EFK-Signaturen vorhanden</div>
              )}

              {signatures.map((sig) => (
                <div key={sig.id} className="nbr-sig-item">
                  <div className="nbr-sig-info">
                    <div className="nbr-sig-name">
                      {sig.efkName}
                      {sig.isDefault && <span className="nbr-complaint-badge resolved" style={{ marginLeft: 6 }}>Standard</span>}
                    </div>
                    {sig.efkBetrieb && <div className="nbr-cell-sub">{sig.efkBetrieb}</div>}
                    {sig.efkEintragNr && <div className="nbr-cell-sub">Nr. {sig.efkEintragNr}</div>}
                  </div>
                  <div className="nbr-sig-preview">
                    <img
                      src={`/api/signatures/${sig.id}/image`}
                      alt="Signatur"
                      style={{ maxHeight: 40, maxWidth: 120, objectFit: "contain" }}
                    />
                  </div>
                  <div className="nbr-sig-actions">
                    {!sig.isDefault && (
                      <button className="nbr-btn nbr-btn-sm" onClick={() => handleSetDefault(sig.id)}>Standard</button>
                    )}
                    <button className="nbr-btn nbr-btn-sm" style={{ color: "#f87171" }} onClick={() => handleDelete(sig.id)}>
                      <X size={12} />
                    </button>
                  </div>
                </div>
              ))}

              {/* Neue Signatur erstellen */}
              {showForm ? (
                <div className="nbr-sig-form">
                  {/* EFK-Daten */}
                  <input
                    type="text"
                    placeholder="EFK-Name *"
                    value={formData.efkName}
                    onChange={(e) => setFormData({ ...formData, efkName: e.target.value })}
                    className="nbr-input"
                  />
                  <input
                    type="text"
                    placeholder="Betrieb"
                    value={formData.efkBetrieb}
                    onChange={(e) => setFormData({ ...formData, efkBetrieb: e.target.value })}
                    className="nbr-input"
                  />
                  <input
                    type="text"
                    placeholder="Eintragungsnummer"
                    value={formData.efkEintragNr}
                    onChange={(e) => setFormData({ ...formData, efkEintragNr: e.target.value })}
                    className="nbr-input"
                  />
                  <label className="nbr-checkbox-label">
                    <input
                      type="checkbox"
                      checked={formData.isDefault}
                      onChange={(e) => setFormData({ ...formData, isDefault: e.target.checked })}
                    />
                    Als Standard setzen
                  </label>

                  {/* Modus-Tabs: Zeichnen / Hochladen */}
                  <div className="nbr-sig-tabs">
                    <button
                      className={`nbr-sig-tab ${inputMode === "draw" ? "active" : ""}`}
                      onClick={() => setInputMode("draw")}
                    >
                      <Pen size={12} /> Zeichnen
                    </button>
                    <button
                      className={`nbr-sig-tab ${inputMode === "upload" ? "active" : ""}`}
                      onClick={() => setInputMode("upload")}
                    >
                      <Upload size={12} /> Hochladen
                    </button>
                  </div>

                  {/* Zeichnen-Modus */}
                  {inputMode === "draw" && (
                    <div className="nbr-sig-draw-area">
                      {drawnSignature ? (
                        <div className="nbr-sig-drawn-preview">
                          <img src={drawnSignature} alt="Gezeichnete Signatur" />
                          <button
                            className="nbr-btn nbr-btn-sm"
                            onClick={() => setDrawnSignature(null)}
                            style={{ position: "absolute", top: 4, right: 4 }}
                          >
                            <Trash2 size={12} /> Neu zeichnen
                          </button>
                        </div>
                      ) : (
                        <InlineSignaturePad
                          onSave={(base64) => setDrawnSignature(base64)}
                        />
                      )}
                    </div>
                  )}

                  {/* Hochladen-Modus */}
                  {inputMode === "upload" && (
                    <div style={{ marginTop: 4 }}>
                      <input
                        type="file"
                        accept="image/png,image/jpeg,image/svg+xml"
                        onChange={(e) => setFile(e.target.files?.[0] || null)}
                        className="nbr-file-input"
                      />
                    </div>
                  )}

                  {/* Aktionen */}
                  <div className="nbr-response-actions" style={{ marginTop: 8 }}>
                    <button className="nbr-btn" onClick={() => { setShowForm(false); setDrawnSignature(null); setFile(null); }}>
                      Abbrechen
                    </button>
                    {inputMode === "draw" ? (
                      <button
                        className="nbr-btn nbr-btn-primary"
                        onClick={handleSaveDrawn}
                        disabled={!drawnSignature || !formData.efkName || saving}
                      >
                        {saving ? <Loader2 size={12} className="nbr-spin" /> : <Check size={12} />} Speichern
                      </button>
                    ) : (
                      <button
                        className="nbr-btn nbr-btn-primary"
                        onClick={handleUpload}
                        disabled={!file || !formData.efkName || saving}
                      >
                        {saving ? <Loader2 size={12} className="nbr-spin" /> : <Upload size={12} />} Hochladen
                      </button>
                    )}
                  </div>
                </div>
              ) : (
                <button className="nbr-btn" style={{ marginTop: 8 }} onClick={() => setShowForm(true)}>
                  <Pen size={12} /> Neue Signatur
                </button>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// INLINE SIGNATURE PAD (Canvas-Zeichenfeld)
// ═══════════════════════════════════════════════════════════════════════════════

function InlineSignaturePad({ onSave }: { onSave: (signatureBase64: string) => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isDrawing, setIsDrawing] = useState(false);
  const [hasSignature, setHasSignature] = useState(false);
  const [paths, setPaths] = useState<{ x: number; y: number }[][]>([]);
  const [currentPath, setCurrentPath] = useState<{ x: number; y: number }[]>([]);
  const width = 480;
  const height = 180;

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = width * dpr;
    canvas.height = height * dpr;
    canvas.style.width = `${width}px`;
    canvas.style.height = `${height}px`;
    ctx.scale(dpr, dpr);
    drawBackground(ctx);
  }, []);

  const drawBackground = (ctx: CanvasRenderingContext2D) => {
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, width, height);
    ctx.strokeStyle = "#e2e8f0";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(20, height - 30);
    ctx.lineTo(width - 20, height - 30);
    ctx.stroke();
    ctx.strokeStyle = "#1e293b";
    ctx.lineWidth = 2;
  };

  const redrawCanvas = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    drawBackground(ctx);
    ctx.strokeStyle = "#1e293b";
    ctx.lineWidth = 2;
    ctx.lineCap = "round";
    ctx.lineJoin = "round";
    paths.forEach(p => {
      if (p.length < 2) return;
      ctx.beginPath();
      ctx.moveTo(p[0].x, p[0].y);
      for (let i = 1; i < p.length; i++) ctx.lineTo(p[i].x, p[i].y);
      ctx.stroke();
    });
  }, [paths]);

  useEffect(() => { redrawCanvas(); }, [redrawCanvas]);

  const getCoords = (e: React.MouseEvent | React.TouchEvent) => {
    const canvas = canvasRef.current;
    if (!canvas) return { x: 0, y: 0 };
    const rect = canvas.getBoundingClientRect();
    if ("touches" in e) {
      const t = e.touches[0];
      return { x: t.clientX - rect.left, y: t.clientY - rect.top };
    }
    return { x: e.clientX - rect.left, y: e.clientY - rect.top };
  };

  const startDrawing = (e: React.MouseEvent | React.TouchEvent) => {
    e.preventDefault();
    setIsDrawing(true);
    const coords = getCoords(e);
    setCurrentPath([coords]);
    const ctx = canvasRef.current?.getContext("2d");
    if (ctx) { ctx.beginPath(); ctx.moveTo(coords.x, coords.y); }
  };

  const draw = (e: React.MouseEvent | React.TouchEvent) => {
    if (!isDrawing) return;
    e.preventDefault();
    const coords = getCoords(e);
    setCurrentPath(prev => [...prev, coords]);
    const ctx = canvasRef.current?.getContext("2d");
    if (ctx) {
      ctx.strokeStyle = "#1e293b";
      ctx.lineWidth = 2;
      ctx.lineCap = "round";
      ctx.lineJoin = "round";
      ctx.lineTo(coords.x, coords.y);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(coords.x, coords.y);
    }
    setHasSignature(true);
  };

  const stopDrawing = () => {
    if (!isDrawing) return;
    setIsDrawing(false);
    if (currentPath.length > 1) setPaths(prev => [...prev, currentPath]);
    setCurrentPath([]);
  };

  const handleClear = () => {
    setPaths([]);
    setCurrentPath([]);
    setHasSignature(false);
  };

  const handleUndo = () => {
    if (paths.length === 0) return;
    setPaths(prev => prev.slice(0, -1));
    if (paths.length === 1) setHasSignature(false);
  };

  const handleSave = () => {
    if (!hasSignature) return;
    const exportCanvas = document.createElement("canvas");
    const ctx = exportCanvas.getContext("2d");
    if (!ctx) return;
    exportCanvas.width = width;
    exportCanvas.height = height;
    ctx.clearRect(0, 0, width, height);
    ctx.strokeStyle = "#1e293b";
    ctx.lineWidth = 2;
    ctx.lineCap = "round";
    ctx.lineJoin = "round";
    paths.forEach(p => {
      if (p.length < 2) return;
      ctx.beginPath();
      ctx.moveTo(p[0].x, p[0].y);
      for (let i = 1; i < p.length; i++) ctx.lineTo(p[i].x, p[i].y);
      ctx.stroke();
    });
    onSave(exportCanvas.toDataURL("image/png"));
  };

  return (
    <div className="nbr-sigpad">
      <div className="nbr-sigpad-canvas-wrap">
        <canvas
          ref={canvasRef}
          onMouseDown={startDrawing}
          onMouseMove={draw}
          onMouseUp={stopDrawing}
          onMouseLeave={stopDrawing}
          onTouchStart={startDrawing}
          onTouchMove={draw}
          onTouchEnd={stopDrawing}
          style={{ touchAction: "none" }}
        />
        {!hasSignature && (
          <div className="nbr-sigpad-placeholder">Hier unterschreiben</div>
        )}
      </div>
      <div className="nbr-sigpad-actions">
        <button className="nbr-btn nbr-btn-sm" onClick={handleClear} disabled={!hasSignature}>
          <Trash2 size={11} /> Löschen
        </button>
        <button className="nbr-btn nbr-btn-sm" onClick={handleUndo} disabled={paths.length === 0}>
          <Undo2 size={11} /> Rückgängig
        </button>
        <div style={{ flex: 1 }} />
        <button className="nbr-btn nbr-btn-primary nbr-btn-sm" onClick={handleSave} disabled={!hasSignature}>
          <Check size={11} /> Übernehmen
        </button>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// CUSTOMER SIGNATURE PAD (für VDE-Formulare)
// ═══════════════════════════════════════════════════════════════════════════════

function CustomerSignatureSection({
  vdeFormularSetId,
  showToast,
}: {
  vdeFormularSetId: number;
  showToast: (msg: string, type: "success" | "error") => void;
}) {
  const [showPad, setShowPad] = useState(false);
  const [saving, setSaving] = useState(false);
  const [signed, setSigned] = useState(false);

  const handleSignatureSave = async (base64: string) => {
    setSaving(true);
    try {
      await apiPost(`/api/vde/sets/${vdeFormularSetId}/sign`, {
        signatur: base64,
      });
      showToast("Kunden-Unterschrift gespeichert", "success");
      setSigned(true);
      setShowPad(false);
    } catch {
      showToast("Speichern fehlgeschlagen", "error");
    }
    setSaving(false);
  };

  if (signed) {
    return (
      <div className="nbr-customer-sig-done">
        <CheckCircle2 size={14} /> Kunden-Unterschrift gespeichert
      </div>
    );
  }

  return (
    <div className="nbr-customer-sig">
      {showPad ? (
        <div>
          <div style={{ fontSize: 12, color: "#a1a1aa", marginBottom: 6 }}>
            Kunden-Unterschrift für VDE-Formulare zeichnen:
          </div>
          <InlineSignaturePad
            onSave={handleSignatureSave}
          />
          {saving && (
            <div className="nbr-loading" style={{ padding: 8 }}>
              <Loader2 size={14} className="nbr-spin" /> Speichern...
            </div>
          )}
          <button className="nbr-btn nbr-btn-sm" style={{ marginTop: 4 }} onClick={() => setShowPad(false)}>
            Abbrechen
          </button>
        </div>
      ) : (
        <button className="nbr-btn nbr-btn-sm" onClick={() => setShowPad(true)}>
          <Pen size={12} /> Kunden-Unterschrift zeichnen
        </button>
      )}
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// SHARED COMPONENTS
// ═══════════════════════════════════════════════════════════════════════════════

function StatusBadge({ status }: { status: string }) {
  const info = STATUS_LABELS[status] || { label: status, color: "#71717a" };
  return (
    <span className="nbr-status-badge" style={{ background: `${info.color}20`, color: info.color, borderColor: `${info.color}40` }}>
      {info.label}
    </span>
  );
}

function ResolveBadge({ status }: { status: string }) {
  const info = RESOLVE_STATUS_LABELS[status] || { label: status, color: "#71717a" };
  return (
    <span className="nbr-status-badge" style={{ background: `${info.color}20`, color: info.color, borderColor: `${info.color}40`, fontSize: 10 }}>
      {info.label}
    </span>
  );
}

function StatBadge({ label, count, color }: { label: string; count: number; color: string }) {
  return (
    <span className="nbr-stat-badge" style={{ borderColor: `${color}40` }}>
      <span className="nbr-stat-count" style={{ color }}>{count}</span>
      <span className="nbr-stat-label">{label}</span>
    </span>
  );
}

function CollapsibleSection({
  title,
  defaultOpen = false,
  children,
}: {
  title: string;
  defaultOpen?: boolean;
  children: React.ReactNode;
}) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div className="nbr-section">
      <button className="nbr-section-toggle" onClick={() => setOpen(!open)}>
        <span>{open ? "▼" : "▶"} {title}</span>
      </button>
      {open && <div className="nbr-section-content">{children}</div>}
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════════

function timeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `vor ${mins}m`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `vor ${hours}h`;
  const days = Math.floor(hours / 24);
  return `vor ${days}d`;
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function groupAttachmentsByType(attachments: AttachmentRecord[]): [string, AttachmentRecord[]][] {
  const groups: Record<string, AttachmentRecord[]> = {};
  for (const a of attachments) {
    const type = a.documentType || "Sonstige";
    if (!groups[type]) groups[type] = [];
    groups[type].push(a);
  }
  return Object.entries(groups).sort(([a], [b]) => a.localeCompare(b));
}
